favicon: null
name: thomasgould
opengraph:
  image: null
  type: null
  appId: null
collections:
  - index:
      path: /
      number: 15
      paginate: true
      navigable: true
    feed:
      path: /rss.xml
      format: rss
      number: 10
    permalink:
      path: '/:title/'
purpose: []
color:
  saturation: 0.5507687313947827
  brandStrength: 0.379331
  lightness: 0.6981624788604677
  brandColors:
    - '#2F2620'
    - '#C6895C'
    - '#E7E2DF'
    - '#9A6641'
    - '#A4A189'
  rhythmicContrast: 0.3416192068252712
typography_spectrum: 0.336174571653828
cta:
  bucket: null
  version: null
  domain: null
layout_spectrum: 0.3859928615856916
analytics:
  twitter: null
  google: null
  facebook: null
